"use client";

import { useMemo, useState } from "react";
import { FileCheck2, ReceiptText } from "lucide-react";
import { limit, query, where } from "firebase/firestore";
import { useAuthenticatedApi } from "@/hooks/use-authenticated-api";
import { AuthenticatedApiError } from "@/lib/authenticated-api-client";
import { AccountPlanTreeSelect } from "@/components/purchasing/account-plan-tree-select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { useFinancialCollection } from "../hooks/use-financial-collection";
import { financialCollection } from "../lib/repositories";
import { formatBRL } from "../cash-closures/money";
import { FEE_LABELS, type FeePreview, type FeeRecordView, type FeeRequest } from "./contracts";

type Account = { id: string; name: string; parentId?: string; active?: boolean; is_dre_account?: boolean };
type Center = { id: string; name: string; active?: boolean; unitIds: string[] };
const date = (value: string) => value.split("-").reverse().join("/");

export function AcquirerFeesPanel({ kioskId, mappingId, stoneCode }: Pick<FeeRequest, "kioskId" | "mappingId" | "stoneCode">) {
  const api = useAuthenticatedApi();
  const [referenceDate, setReferenceDate] = useState("");
  const [source, setSource] = useState<FeeRequest["source"]>("pix");
  const [preview, setPreview] = useState<FeePreview | null>(null);
  const [history, setHistory] = useState<FeeRecordView[]>([]);
  const [selected, setSelected] = useState("");
  const [mode, setMode] = useState<"create" | "link">("create");
  const [account, setAccount] = useState(""); const [center, setCenter] = useState(""); const [existingId, setExistingId] = useState("");
  const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [candidates, setCandidates] = useState<Array<{ id: string; description: string; totalValue: number }>>([]);
  const [cursor, setCursor] = useState<string | null>(null);
  const editing = Boolean(selected);
  const accountQuery = useMemo(() => editing ? query(financialCollection<Account>("accounts"), limit(501)) : null, [editing]);
  const centerQuery = useMemo(() => editing ? query(financialCollection<Center>("resultCenters"), where("unitIds", "array-contains", kioskId), limit(51)) : null, [editing, kioskId]);
  const accounts = useFinancialCollection<Account>(accountQuery); const centers = useFinancialCollection<Center>(centerQuery);
  const overflow = (accounts.data?.length ?? 0) > 500 || (centers.data?.length ?? 0) > 50;
  const centerOptions = (centers.data ?? []).filter(row => row.active !== false && row.unitIds.length === 1 && row.unitIds[0] === kioskId);
  const batch = preview?.batches.find(row => row.id === selected); const record = history.find(row => row.id === selected);
  const request: FeeRequest = { kioskId, mappingId, stoneCode, referenceDate, source };
  const run = async (work: () => Promise<void>) => {
    if (busy) return; setBusy(true); setError(""); setMessage("");
    try { await work(); } catch (caught) { setError(caught instanceof AuthenticatedApiError ? caught.message : "Não foi possível concluir. Consulte o histórico antes de repetir."); } finally { setBusy(false); }
  };
  const reset = () => { setPreview(null); setHistory([]); setSelected(""); setCandidates([]); setCursor(null); setError(""); setMessage(""); };
  const choose = (id: string) => { setSelected(id); setAccount(""); setCenter(""); setReason(""); setConfirmed(false); setExistingId(""); setCandidates([]); setCursor(null); };
  // A ação compacta de histórico equivale a “Consultar registros anteriores”.
  const loadHistory = async () => { const result = await api<{ records: FeeRecordView[] }>(`/api/financial/acquirer-fees?${new URLSearchParams(request)}`); setHistory(result.records); };
  const loadCandidates = (next?: string) => run(async () => {
    if (!batch) return;
    const params = new URLSearchParams({ ...request, referenceDate: batch.competenceDate, resultCenterId: center }); if (next) params.set("cursor", next);
    const result = await api<{ candidates: typeof candidates; nextCursor: string | null }>(`/api/financial/acquirer-fees?${params}`);
    setCandidates(current => next ? [...current, ...result.candidates] : result.candidates); setCursor(result.nextCursor);
  });
  const save = () => run(async () => {
    const action = record?.active ? { action: "cancel" as const, request, batchId: selected, reason }
      : mode === "link" ? { action: "link" as const, request, batchId: selected, fingerprint: batch?.fingerprint ?? "", existingExpenseId: existingId, ...(reason ? { reason } : {}) }
        : { action: "create" as const, request, batchId: selected, fingerprint: batch?.fingerprint ?? "", accountPlanId: account, resultCenterId: center, confirmedNoManualExpense: confirmed, ...(reason ? { reason } : {}) };
    await api("/api/financial/acquirer-fees", { method: "POST", json: action }); await loadHistory(); setSelected(""); setMessage("Registro atualizado. Nenhum pagamento ou débito bancário foi criado.");
  });
  const activeRecordsOutsidePreview = history.filter(row => row.active && !preview?.batches.some(item => item.id === row.id));
  const selectedTitle = batch ? FEE_LABELS[batch.kind] : record ? FEE_LABELS[record.kind] : "Grupo de taxa";
  const saveDisabled = busy || (record?.active ? reason.trim().length < 3 : !batch || overflow || Boolean(accounts.error) || Boolean(centers.error) || mode === "create" && (!account || !center || !confirmed) || mode === "link" && !existingId);

  return <Card className="rounded-2xl border-ds-border bg-white"><CardHeader className="pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-ds-accent-ink">Etapa 03 · retenções explícitas</p><CardTitle className="mt-1 flex items-center gap-2 text-lg"><ReceiptText className="h-5 w-5 text-ds-accent-ink" />Taxas praticadas e apropriação</CardTitle><CardDescription className="mt-1">Consulte retenções explícitas da Stone e confirme cada grupo como despesa quitada na origem. Não haverá outra saída no banco.</CardDescription></div><FileCheck2 className="h-6 w-6 text-ds-accent-ink" aria-hidden="true" /></div></CardHeader>
    <CardContent className="space-y-4"><div className="rounded-2xl border border-ds-border bg-ds-input p-4"><div className="flex flex-wrap gap-2" role="group" aria-label="Fonte de taxas"><Button type="button" size="sm" variant={source === "pix" ? "default" : "outline"} className={source === "pix" ? "bg-ds-accent hover:bg-ds-accent-ink" : ""} onClick={() => { setSource("pix"); reset(); }}>Pix <span className="ml-1 opacity-70">arquivo já processado</span></Button><Button type="button" size="sm" variant={source === "cards" ? "default" : "outline"} className={source === "cards" ? "bg-ds-accent hover:bg-ds-accent-ink" : ""} onClick={() => { setSource("cards"); reset(); }}>Cartões e antecipação <span className="ml-1 opacity-70">pagamentos</span></Button></div><div className="mt-4 grid gap-3 md:grid-cols-[minmax(220px,0.55fr)_auto_1fr] md:items-end"><label className="grid gap-1.5 text-sm font-semibold text-ds-ink-2">{source === "pix" ? "Dia das vendas Pix" : "Dia do pagamento informado pela Stone"}<Input type="date" value={referenceDate} onChange={event => { setReferenceDate(event.target.value); reset(); }} /></label><div className="flex flex-wrap gap-2"><Button type="button" disabled={busy || !referenceDate} onClick={() => void run(async () => { const data = await api<FeePreview>("/api/financial/acquirer-fees", { method: "POST", json: { action: "preview", request } }); setPreview(data); setHistory(data.records); setSelected(""); })} className="bg-ds-accent hover:bg-ds-accent-ink">{busy ? "Consultando…" : "Consultar prévia — sem gravar"}</Button><Button type="button" variant="outline" disabled={busy || !referenceDate} onClick={() => void run(loadHistory)}>Registros anteriores</Button></div><p className="text-xs leading-5 text-muted-foreground">Pix/MDR pertencem ao dia da venda; antecipação, ao dia da retenção. Decimais são somados antes do arredondamento.</p></div></div>
      {error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}{message ? <p role="status" className="rounded-xl border border-ds-border bg-ds-ok-bg p-3 text-sm text-ds-ok">{message}</p> : null}
      {preview?.pending.map((text, index) => <p key={index} className="rounded-xl border border-ds-alert-border bg-ds-warn-bg p-3 text-sm text-ds-alert-ink">{text}</p>)}
      {preview && !preview.batches.length ? <div role="status" className="rounded-2xl border border-dashed border-ds-border-input px-6 py-10 text-center"><p className="font-bold">Nenhum grupo elegível neste recorte.</p><p className="mt-1 text-sm text-muted-foreground">Isso não comprova ausência de taxas; confira as pendências acima.</p></div> : null}
      {preview?.batches.length || activeRecordsOutsidePreview.length ? <section className="overflow-hidden rounded-2xl border border-ds-border"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-ds-divider bg-ds-input px-4 py-3"><div><h3 className="text-sm font-extrabold">{preview ? `Prévia · ${source === "pix" ? "Pix" : "Cartões e antecipação"}` : "Registros anteriores"}</h3><p className="mt-1 text-xs text-muted-foreground">Abra um grupo para conferir as evidências e sua classificação.</p></div>{preview ? <span className="font-mono text-sm font-bold">{formatBRL(preview.batches.reduce((sum, item) => sum + item.amountCents, 0))}</span> : null}</div><div className="divide-y divide-ds-divider">
        {(preview?.batches ?? []).map(item => { const registered = history.find(row => row.id === item.id && row.active); return <button key={item.id} type="button" onClick={() => choose(item.id)} className="grid w-full gap-3 px-4 py-3 text-left transition hover:bg-ds-input focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ds-accent md:grid-cols-[minmax(0,1fr)_150px_130px_130px] md:items-center"><div><p className="font-semibold">{FEE_LABELS[item.kind]}</p><p className="mt-1 text-xs text-muted-foreground">Competência {date(item.competenceDate)} · retenção {date(item.settledOn)}</p></div><span className="text-xs text-muted-foreground">{item.members.length} evidência(s)</span><span className="font-mono font-bold">{formatBRL(item.amountCents)}</span><span className={`text-xs font-bold ${registered ? "text-ds-ok" : "text-ds-accent-ink"}`}>{registered ? registered.fingerprint === item.fingerprint ? "Já registrado" : "Origem alterada" : "Classificar →"}</span></button>; })}
        {activeRecordsOutsidePreview.map(item => <button key={item.id} type="button" onClick={() => choose(item.id)} className="grid w-full gap-3 px-4 py-3 text-left transition hover:bg-ds-input md:grid-cols-[minmax(0,1fr)_150px_130px_130px]"><div><p className="font-semibold">{FEE_LABELS[item.kind]}</p><p className="mt-1 text-xs text-muted-foreground">Registro anterior fora da prévia atual · despesa {item.expenseId}</p></div><span className="text-xs text-muted-foreground">Competência {date(item.competenceDate)}</span><span className="font-mono font-bold">{formatBRL(item.amountCents)}</span><span className="text-xs font-bold text-ds-accent-ink">Corrigir →</span></button>)}
      </div></section> : null}
      {overflow ? <p role="alert" className="text-sm text-destructive">Catálogo acima do limite. Nenhum lançamento será feito; revise os cadastros.</p> : null}
    </CardContent>
    <Sheet open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(""); }}><SheetContent className="w-full overflow-y-auto border-ds-border p-5 sm:max-w-xl sm:p-6"><SheetHeader className="pr-8"><SheetTitle>{selectedTitle}</SheetTitle><SheetDescription>{record?.active ? "Corrija ou estorne o vínculo preservando o histórico." : "Confira as evidências antes de registrar a despesa quitada na origem."}</SheetDescription></SheetHeader>{selected ? <div className="mt-6 space-y-5">
      <section className="rounded-2xl border border-ds-border bg-ds-input p-4"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Competência</dt><dd className="mt-1 font-semibold">{batch ? date(batch.competenceDate) : record ? date(record.competenceDate) : "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Retenção</dt><dd className="mt-1 font-semibold">{batch ? date(batch.settledOn) : record ? date(record.settledOn) : "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Valor arredondado</dt><dd className="mt-1 font-mono font-bold">{batch ? formatBRL(batch.amountCents) : record ? formatBRL(record.amountCents) : "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Registro</dt><dd className="mt-1">{record?.active ? `Despesa ${record.expenseId}` : "A confirmar"}</dd></div></dl></section>
      {batch ? <section><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-extrabold">Evidências · {batch.members.length} parcela(s)</h3><span className="text-xs text-muted-foreground">soma decimal antes do arredondamento</span></div><ul className="mt-3 space-y-2">{batch.members.slice(0, 20).map(member => <li key={member.id} className="rounded-xl border border-ds-border p-3 text-sm"><div className="flex justify-between gap-3"><span className="font-mono font-semibold">{member.evidence.transactionId} / {member.evidence.installment}</span><span className="font-mono">R$ {member.amountDecimal.replace(".", ",")}</span></div><p className="mt-1 text-xs text-muted-foreground">Bruto R$ {member.evidence.gross.replace(".", ",")} · PaymentId {member.evidence.paymentId}</p></li>)}</ul>{batch.members.length > 20 ? <p className="mt-2 text-xs text-muted-foreground">Mostrando 20 de {batch.members.length} evidências.</p> : null}</section> : null}
      <section className="rounded-2xl border border-ds-border p-4"><h3 className="text-sm font-extrabold">{record?.active ? "Estornar vínculo com histórico" : "Confirmar despesa quitada na origem"}</h3>{record?.active ? <p className="mt-2 text-sm text-muted-foreground">Uma despesa criada aqui será cancelada; uma despesa vinculada retorna ao estado anterior, preservando notas e anexos.</p> : <><div className="mt-3 flex rounded-xl bg-muted p-1"><Button type="button" variant={mode === "create" ? "secondary" : "ghost"} className="flex-1" onClick={() => setMode("create")}>Criar despesa</Button><Button type="button" variant={mode === "link" ? "secondary" : "ghost"} className="flex-1" onClick={() => setMode("link")}>Vincular existente</Button></div><label className="mt-3 grid gap-1.5 text-sm font-semibold">Centro exclusivo da unidade<select className="h-10 rounded-xl border bg-background px-3 text-sm" value={center} onChange={event => { setCenter(event.target.value); setCandidates([]); setCursor(null); }}><option value="">Selecione</option>{centerOptions.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{mode === "create" ? <><label className="mt-3 grid gap-1.5 text-sm font-semibold">Plano de contas<AccountPlanTreeSelect placeholder="Selecione uma conta de despesa" value={account} onChange={setAccount} options={(accounts.data ?? []).filter(item => item.active !== false && item.is_dre_account !== false)} /></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />Conferi que esta taxa não foi lançada manualmente.</label></> : <><Button type="button" className="mt-3" variant="outline" disabled={!center || busy} onClick={() => void loadCandidates()}>Buscar despesas da competência e centro</Button><label className="mt-3 grid gap-1.5 text-sm font-semibold">ID da despesa existente<Input value={existingId} onChange={event => setExistingId(event.target.value)} placeholder="Cole o ID ou selecione abaixo" /></label>{candidates.map(item => <Button key={item.id} type="button" variant="outline" className="mt-2 h-auto w-full justify-between whitespace-normal text-left" onClick={() => setExistingId(item.id)}>{item.description}<span className="font-mono">{formatBRL(Math.round(item.totalValue * 100))}</span></Button>)}{cursor ? <Button type="button" variant="outline" className="mt-2" onClick={() => void loadCandidates(cursor)}>Próxima página</Button> : null}</>}</>}</section>
      <label className="grid gap-1.5 text-sm font-semibold">Motivo {record?.active ? "(obrigatório)" : "(obrigatório para correção/reclassificação)"}<Textarea value={reason} maxLength={500} onChange={event => setReason(event.target.value)} /></label><p className="text-xs text-muted-foreground">Esta confirmação não cria pagamento, split, obrigação ou débito bancário.</p><Button type="button" disabled={saveDisabled} onClick={() => void save()} className={record?.active ? "bg-ds-danger hover:bg-ds-danger" : "bg-ds-accent hover:bg-ds-accent-ink"}>{record?.active ? "Confirmar estorno do vínculo" : "Confirmar — sem novo pagamento"}</Button>
    </div> : null}</SheetContent></Sheet>
  </Card>;
}
