import type { Config } from "tailwindcss";

import tailwindcssAnimate from "tailwindcss-animate";
const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
    },
    extend: {
      fontFamily: {
        sans:     ["Geist", "sans-serif"],
        headline: ["Geist", "sans-serif"],
        mono:     ["Geist Mono", "monospace"],
        ds:       ["'Inter Tight Variable'", "'Inter Tight'", "Inter", "system-ui", "sans-serif"],
        "ds-mono": ["'JetBrains Mono'", "'Geist Mono'", "ui-monospace", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
        ds: {
          page: "var(--ds-bg-page)",
          topbar: "var(--ds-bg-topbar)",
          surface: "var(--ds-surface)",
          warm: "var(--ds-surface-warm)",
          input: "var(--ds-surface-input)",
          muted: "var(--ds-surface-muted)",
          seg: "var(--ds-surface-seg)",
          dark: "var(--ds-surface-dark)",
          "dark-hover": "var(--ds-surface-dark-hover)",
          border: "var(--ds-border)",
          "border-input": "var(--ds-border-input)",
          divider: "var(--ds-divider)",
          ink: "var(--ds-ink)",
          "ink-2": "var(--ds-ink-2)",
          "ink-muted": "var(--ds-ink-muted)",
          "ink-faint": "var(--ds-ink-faint)",
          "on-dark": "var(--ds-ink-on-dark)",
          "on-dark-2": "var(--ds-ink-on-dark-2)",
          "on-dark-muted": "var(--ds-ink-on-dark-muted)",
          "on-dark-sub": "var(--ds-ink-on-dark-sub)",
          "indicator-zero": "var(--ds-indicator-zero)",
          "border-footer": "var(--ds-border-footer)",
          accent: "var(--ds-accent)",
          "accent-hover": "var(--ds-accent-hover)",
          "accent-ink": "var(--ds-accent-ink)",
          "accent-ink-hover": "var(--ds-accent-ink-hover)",
          "accent-soft": "var(--ds-accent-soft)",
          "accent-row": "var(--ds-accent-row)",
          "accent-kicker": "var(--ds-accent-kicker-dark)",
          modal: "var(--ds-modal-accent)",
          "modal-soft": "var(--ds-modal-accent-soft)",
          "modal-ink": "var(--ds-modal-accent-ink)",
          ok: "var(--ds-ok)", "ok-bg": "var(--ds-ok-bg)",
          warn: "var(--ds-warn)", "warn-bg": "var(--ds-warn-bg)",
          danger: "var(--ds-danger)", "danger-bg": "var(--ds-danger-bg)",
          info: "var(--ds-info)", "info-bg": "var(--ds-info-bg)",
          neutral: "var(--ds-neutral)", "neutral-bg": "var(--ds-neutral-bg)",
          "alert-bg": "var(--ds-alert-bg)", "alert-border": "var(--ds-alert-border)", "alert-ink": "var(--ds-alert-ink)",
          "confirm-bg": "var(--ds-confirm-bg)", "confirm-border": "var(--ds-confirm-border)", "confirm-ink": "var(--ds-confirm-ink)",
          disabled: "var(--ds-disabled)",
        },
      },
      borderRadius: {
        "ds-pill": "var(--ds-r-pill)",
        "ds-sm": "var(--ds-r-sm)",
        "ds-md": "var(--ds-r-md)",
        "ds-btn": "var(--ds-r-btn)",
        "ds-btn-lg": "var(--ds-r-btn-lg)",
        "ds-card": "var(--ds-r-card)",
        "ds-card-lg": "var(--ds-r-card-lg)",
        "ds-modal": "var(--ds-r-modal)",
        "ds-panel": "var(--ds-r-panel)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        "ds-lift": "var(--ds-shadow-lift)",
        "ds-menu": "var(--ds-shadow-menu)",
        "ds-modal": "var(--ds-shadow-modal)",
        "ds-panel": "var(--ds-shadow-panel)",
        "ds-cta": "var(--ds-shadow-cta)",
        "ds-side": "var(--ds-shadow-side)",
      },
      transitionTimingFunction: { "ds-lift": "var(--ds-ease-lift)" },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'shake': 'shake 0.5s ease-in-out',
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
