'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Calendar, CheckCircle2, Clock } from 'lucide-react';

type Info = { candidateName: string; alreadyResponded: boolean };

export default function ClinicAsoSchedulePage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [info, setInfo] = useState<Info | null>(null); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { void params.then(({ token: value }) => { setToken(value); return fetch(`/api/hr/aso/clinic/${value}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInfo(data); setSent(data.alreadyResponded); }).catch(caught => setError(caught instanceof Error ? caught.message : 'Falha ao abrir o link.')); }); }, [params]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); const response = await fetch(`/api/hr/aso/clinic/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error || 'Falha ao enviar.'); setSent(true); }
  return <main className="min-h-screen bg-[#fff8fc] px-4 py-10 text-slate-900"><div className="mx-auto max-w-md rounded-3xl border border-pink-100 bg-white p-6 shadow-xl shadow-pink-100/50 sm:p-9"><img src="https://op.coalashakes.com/coala-email-logo.jpg" alt="Coala Shakes" className="h-auto w-40"/><h1 className="mt-6 text-2xl font-black">Data e horário do ASO</h1>{info ? <p className="mt-2 text-sm text-slate-600">Colaboradora: <b>{info.candidateName}</b></p> : null}{error ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p> : null}{sent ? <div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="h-7 w-7"/><p className="mt-2 font-black">Obrigado!</p><p className="mt-1 text-sm">O agendamento foi enviado ao RH da Coala Shakes.</p></div> : info ? <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-bold"><Calendar className="mr-2 inline h-4 w-4"/>Data<input name="date" type="date" required className="mt-2 h-11 w-full rounded-xl border px-3"/></label><label className="block text-sm font-bold"><Clock className="mr-2 inline h-4 w-4"/>Horário<input name="time" type="time" required className="mt-2 h-11 w-full rounded-xl border px-3"/></label><button disabled={busy} className="h-12 w-full rounded-xl bg-pink-500 font-black text-white disabled:opacity-50">{busy ? 'Enviando...' : 'Enviar agendamento'}</button></form> : !error ? <p className="mt-6 text-sm">Carregando...</p> : null}</div></main>;
}
