'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AlertTriangle, Calendar, CheckCircle2, Clock } from 'lucide-react';

type Info = { candidateName: string; expectedAdmissionDate: string | null; alreadyResponded: boolean };

function formatDateOnly(value?: string | null) {
  if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return 'não informada';
  const [year, month, day] = value.split('-');
  return `${day}/${month}/${year}`;
}

export default function ClinicAsoSchedulePage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [info, setInfo] = useState<Info | null>(null); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [appointmentDate, setAppointmentDate] = useState(''); const [sentAfterAdmission, setSentAfterAdmission] = useState(false);
  useEffect(() => { void params.then(({ token: value }) => { setToken(value); return fetch(`/api/hr/aso/clinic/${value}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInfo(data); setSent(data.alreadyResponded); }).catch(caught => setError(caught instanceof Error ? caught.message : 'Falha ao abrir o link.')); }); }, [params]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); const response = await fetch(`/api/hr/aso/clinic/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error || 'Falha ao enviar.'); setSentAfterAdmission(data.appointmentAfterAdmission === true); setSent(true); }
  const appointmentAfterAdmission = Boolean(info?.expectedAdmissionDate && appointmentDate > info.expectedAdmissionDate);
  return <main className="min-h-screen bg-[#fff8fc] px-4 py-10 text-slate-900"><div className="mx-auto max-w-md rounded-3xl border border-pink-100 bg-white p-6 shadow-xl shadow-pink-100/50 sm:p-9"><img src="https://op.coalashakes.com/coala-email-logo.jpg" alt="Coala Shakes" className="h-auto w-40"/><h1 className="mt-6 text-2xl font-black">Data e horário do ASO</h1>{info ? <><p className="mt-2 text-sm text-slate-600">Colaboradora: <b>{info.candidateName}</b></p>{info.expectedAdmissionDate ? <p className="mt-1 text-xs font-semibold text-slate-500">Admissão prevista pela empresa: <b>{formatDateOnly(info.expectedAdmissionDate)}</b>. Informe abaixo a data real disponível para o exame.</p> : null}</> : null}{error ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p> : null}{sent ? <div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="h-7 w-7"/><p className="mt-2 font-black">Obrigado!</p><p className="mt-1 text-sm">O agendamento foi enviado ao RH da Coala Shakes.</p>{sentAfterAdmission ? <p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-800">A data informada é posterior à admissão prevista. O RH foi alertado para revisar o cronograma.</p> : null}</div> : info ? <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-bold"><Calendar className="mr-2 inline h-4 w-4"/>Data<input name="date" type="date" required value={appointmentDate} onChange={event => setAppointmentDate(event.target.value)} className="mt-2 h-11 w-full rounded-xl border px-3"/></label>{appointmentAfterAdmission ? <div role="alert" className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><p className="text-xs font-bold leading-relaxed">Esta data é posterior à admissão prevista em {formatDateOnly(info.expectedAdmissionDate)}. O agendamento será aceito, mas o RH receberá um alerta para revisar a admissão.</p></div> : null}<label className="block text-sm font-bold"><Clock className="mr-2 inline h-4 w-4"/>Horário<input name="time" type="time" required className="mt-2 h-11 w-full rounded-xl border px-3"/></label><button disabled={busy} className="h-12 w-full rounded-xl bg-pink-500 font-black text-white disabled:opacity-50">{busy ? 'Enviando...' : 'Enviar agendamento'}</button></form> : !error ? <p className="mt-6 text-sm">Carregando...</p> : null}</div></main>;
}
