'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, FileUp } from 'lucide-react';

type Info = { candidateName: string; companyName: string; alreadyUploaded: boolean; rejected: boolean; rejectionReason?: string | null };

export default function AccountantRegistryUploadPage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [info, setInfo] = useState<Info | null>(null); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { void params.then(({ token: value }) => { setToken(value); return fetch(`/api/hr/accountant/${value}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInfo(data); }).catch(caught => setError(caught instanceof Error ? caught.message : 'Falha ao abrir o link.')); }); }, [params]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const response = await fetch(`/api/hr/accountant/${token}`, { method: 'POST', body: new FormData(event.currentTarget) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error || 'Falha ao enviar.'); setSent(true); }
  return <main className="min-h-screen bg-[#fff8fc] px-4 py-10 text-slate-900"><div className="mx-auto max-w-xl rounded-3xl border border-pink-100 bg-white p-6 shadow-xl shadow-pink-100/50 sm:p-9"><p className="text-sm font-black uppercase tracking-widest text-pink-500">Coala Shakes · Admissão</p><h1 className="mt-3 text-2xl font-black">Enviar ficha de registro</h1><p className="mt-2 text-sm text-slate-600">Utilize este link exclusivamente para enviar a <b>Ficha de Registro de Empregado</b> de <b>{info?.candidateName || 'colaborador(a)'}</b>.</p>{info?.rejected ? <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800">A ficha anterior precisa ser substituída.{info.rejectionReason ? ` Motivo: ${info.rejectionReason}` : ''}</p> : null}{error ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p> : null}{info ? <>{sent || info.alreadyUploaded ? <div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="h-7 w-7"/><p className="mt-2 font-black">Obrigado! Ficha recebida.</p><p className="mt-1 text-sm">O RH fará a conferência do documento.</p></div> : <form onSubmit={submit} className="mt-6 space-y-4"><label className="block rounded-2xl border-2 border-dashed p-5 text-center text-sm font-bold"><FileUp className="mx-auto mb-2 h-7 w-7 text-pink-500"/>Anexe a Ficha de Registro de Empregado em PDF<input name="file" type="file" accept="application/pdf" required className="mt-3 block w-full text-xs"/></label><button disabled={busy} className="h-12 w-full rounded-xl bg-pink-500 font-black text-white disabled:opacity-50">{busy ? 'Enviando...' : 'Enviar ficha de registro'}</button></form>}</> : !error ? <p className="mt-6 text-sm">Carregando...</p> : null}</div></main>;
}
