"use client";

import { useState } from "react";
import { ArrowRight, CalendarClock } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { PageContainer } from "@/components/layout/page-container";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { AnticipationWorkspace } from "@/features/financial/agent/anticipation-workspace";
import { formatStoneMoney } from "@/features/financial/agent/presentation";
import { FinancialAnalysisNavigation } from "@/features/financial/agent/analysis-navigation";
import type { StoneAnticipationReview } from "@/lib/integrations/stone/anticipation-review";

const money = formatStoneMoney;
const date = (value: string | null) => value ? value.split("-").reverse().join("/") : "Não informada";
const statuses = { paid_early: "Pago antes do vencimento", regular_payment: "Pagamento no prazo ou posterior", needs_review: "Revisar vínculo" };
const tone = { paid_early: "border-violet-200 bg-violet-50 text-violet-950", regular_payment: "border-emerald-200 bg-emerald-50 text-emerald-950", needs_review: "border-amber-200 bg-amber-50 text-amber-950" };
function daysEarly(due: string | null, paid: string | null) { if (!due || !paid) return null; return Math.round((Date.parse(`${due}T12:00:00Z`) - Date.parse(`${paid}T12:00:00Z`)) / 86_400_000); }

export function StoneAnticipationsPage({ agentEntry = false }: { agentEntry?: boolean }) {
  const { isDefaultAdmin } = useAuth(); const [result, setResult] = useState<StoneAnticipationReview | null>(null); const [page, setPage] = useState(0); const [filter, setFilter] = useState<"all" | keyof typeof statuses>("all"); const [selected, setSelected] = useState<StoneAnticipationReview["rows"][number] | null>(null);
  if (!isDefaultAdmin) return <PageContainer surface><p role="alert">Consulta restrita à administração.</p></PageContainer>;
  const ordered = result ? result.rows.filter(row => filter === "all" || row.status === filter).sort((left, right) => ({ paid_early: 0, needs_review: 1, regular_payment: 2 })[left.status] - ({ paid_early: 0, needs_review: 1, regular_payment: 2 })[right.status] || left.transactionId.localeCompare(right.transactionId)) : [];
  const filters: Array<{ id: "all" | keyof typeof statuses; label: string; count: number }> = result ? [{ id: "all", label: "Todas", count: result.rows.length }, { id: "paid_early", label: "Pagas antes do prazo", count: result.summary.earlyCount }, { id: "needs_review", label: "Pendentes de conferência", count: result.summary.pendingCount }, { id: "regular_payment", label: "No prazo ou posteriores", count: result.summary.regularCount }] : [];
  return <PageContainer variant="wide" surface className="space-y-6 py-6">
    {agentEntry ? <header><h1 className="text-2xl font-bold tracking-tight">Coala Financeiro</h1><p className="text-sm text-muted-foreground">Análises guiadas de antecipações e recebíveis por período. Carteira completa, DRE e análise geral de caixa ainda não estão disponíveis neste agente.</p></header> : <PageHeader title="Conferência de antecipações Stone" description="Pagamentos comparados com parcelas originais, sem baixa ou lançamento financeiro." back={{ fallbackHref: "/dashboard/financial/stone-receipts", parentLabel: "Conciliação de recebimentos" }} />}
    {agentEntry ? <FinancialAnalysisNavigation topic="anticipations" /> : null}
    <div role="note" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Custo informado no XML e desconto adicional calculado são evidências distintas. A entrada bancária não é conciliada nesta etapa; confirme o líquido em Crédito bancário × Stone.</div>
    <AnticipationWorkspace onResult={value => { setResult(value); setPage(0); setFilter("all"); setSelected(null); }} />
    {result ? <section className="space-y-4" aria-label="Resultado da conferência"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm text-muted-foreground">StoneCode {result.stoneCode} · pagamentos de {date(result.referenceDate)} · consulta {new Date(result.collectedAt).toLocaleString("pt-BR")}</p><p className="text-sm text-muted-foreground">Arquivo {result.paymentFileId}</p></div>{result.unavailableDates.length || result.skippedDates.length ? <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-950"><strong>Cobertura incompleta.</strong> Datas indisponíveis: {result.unavailableDates.map(date).join(", ") || "nenhuma"}. Datas fora do limite: {result.skippedDates.map(date).join(", ") || "nenhuma"}. Não conclua ausência de antecipação nas parcelas pendentes.</p> : null}
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["Parcelas pagas antes do prazo", String(result.summary.earlyCount), "border-violet-200 bg-violet-50"], ["Bruto dessas parcelas", money(result.summary.gross), "border-[#e6e3dc] bg-white"], ["Líquido informado pela Stone", money(result.summary.paidNet), "border-emerald-200 bg-emerald-50"], ["Desconto adicional calculado", money(result.summary.additionalDiscount), "border-rose-200 bg-rose-50"]].map(([title, value, className]) => <Card key={title} className={`rounded-2xl ${className}`}><CardContent className="p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-muted-foreground">{title}</p><p className="mt-2 font-mono text-xl font-bold">{value}</p></CardContent></Card>)}</div>
      <div className="grid gap-3 rounded-2xl border border-[#e6e3dc] bg-[#faf9f6] p-4 text-sm sm:grid-cols-3"><p><strong>MDR informado</strong><span className="mt-1 block font-mono">{money(result.summary.mdr)}</span></p><p><strong>Custo de antecipação no XML</strong><span className="mt-1 block font-mono">{money(result.summary.anticipationFee)}</span></p><p><strong>Diferença não explicada</strong><span className="mt-1 block font-mono">{money(result.summary.unexplainedDifference)}</span></p></div>
      <div role="group" aria-label="Filtrar parcelas" className="flex flex-wrap gap-2">{filters.map(item => <button key={item.id} type="button" onClick={() => { setFilter(item.id); setPage(0); }} aria-pressed={filter === item.id} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${filter === item.id ? "border-[#1d1d26] bg-[#1d1d26] text-white" : "border-[#e2e0da] bg-white text-[#4a4a55]"}`}>{item.label} <span className="ml-1 opacity-70">{item.count}</span></button>)}</div>
      <section className="overflow-hidden rounded-2xl border border-[#e6e3dc]"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-[#eeeae2] bg-[#faf9f6] px-4 py-3"><div><h2 className="text-sm font-extrabold">Parcelas e evidências do pagamento</h2><p className="mt-1 text-xs text-muted-foreground">Clique em uma linha para ver as evidências completas.</p></div><span className="text-xs text-muted-foreground">{ordered.length ? `${page * 50 + 1}–${Math.min(ordered.length, (page + 1) * 50)} de ${ordered.length}` : ""}</span></div>{ordered.length ? <div className="divide-y divide-[#f1eee8]">{ordered.slice(page * 50, (page + 1) * 50).map(row => { const early = daysEarly(row.originalDueDate, row.paymentDate); return <button key={`${row.transactionId}:${row.installment}`} type="button" onClick={() => setSelected(row)} className="grid w-full gap-3 px-4 py-3 text-left transition hover:bg-[#fdf8fa] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#df2f78] md:grid-cols-[minmax(180px,1fr)_minmax(220px,1.1fr)_120px_150px] md:items-center"><div><p className="font-mono text-xs font-semibold">{row.transactionId} / {row.installment}</p><p className="mt-1 text-xs text-muted-foreground">Venda {date(row.saleDate)} · bruto {money(row.gross)}</p></div><div><p className="text-sm font-semibold">{date(row.originalDueDate)} <ArrowRight className="mx-1 inline h-3.5 w-3.5" aria-hidden="true" /> {date(row.paymentDate)}</p><p className="mt-1 text-xs text-muted-foreground">{row.status === "paid_early" && early !== null ? `${early} dia(s) antes do vencimento` : "pagamento no arquivo Stone"}</p></div><span className="font-mono text-sm font-bold">{money(row.paidNet)}</span><span className={`justify-self-start rounded-full border px-2 py-1 text-[11px] font-bold ${tone[row.status]}`}>{statuses[row.status]}</span></button>; })}</div> : <div role="status" className="px-6 py-12 text-center text-sm text-muted-foreground">{result.rows.length ? "Nenhuma parcela corresponde ao filtro selecionado." : "Nenhuma parcela com evento de pagamento neste arquivo. Isso não comprova ausência de antecipações em outros arquivos."}</div>}{ordered.length > 50 ? <div className="flex items-center justify-end gap-3 border-t border-[#eeeae2] px-4 py-3"><Button type="button" variant="outline" disabled={page === 0} onClick={() => setPage(page - 1)}>Anterior</Button><span className="text-sm">Página {page + 1} de {Math.ceil(ordered.length / 50)}</span><Button type="button" variant="outline" disabled={(page + 1) * 50 >= ordered.length} onClick={() => setPage(page + 1)}>Próxima</Button></div> : null}</section>
      <p className="text-xs text-muted-foreground">Totais somados na precisão original; linhas exibidas com duas casas decimais. Nenhuma alteração na agenda, no caixa ou na DRE.</p>
    </section> : null}
    <Sheet open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null); }}><SheetContent className="w-full overflow-y-auto border-[#e6e3dc] p-5 sm:max-w-xl sm:p-6">{selected ? <><SheetHeader className="pr-8"><SheetTitle>Parcela {selected.transactionId} / {selected.installment}</SheetTitle><SheetDescription>{statuses[selected.status]}{selected.providerAnticipationConfirmed ? " · antecipação explícita no XML" : ""}</SheetDescription></SheetHeader><div className="mt-6 space-y-4"><section className="rounded-2xl border border-[#e6e3dc] bg-[#faf9f6] p-4"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Venda</dt><dd className="mt-1">{date(selected.saleDate)}</dd></div><div><dt className="text-xs text-muted-foreground">Vencimento original</dt><dd className="mt-1">{date(selected.originalDueDate)}</dd></div><div><dt className="text-xs text-muted-foreground">Pagamento Stone</dt><dd className="mt-1">{date(selected.paymentDate)}</dd></div><div><dt className="text-xs text-muted-foreground">Líquido pago</dt><dd className="mt-1 font-mono font-semibold">{money(selected.paidNet)}</dd></div><div><dt className="text-xs text-muted-foreground">Líquido original</dt><dd className="mt-1 font-mono">{money(selected.originalNet)}</dd></div><div><dt className="text-xs text-muted-foreground">Bruto</dt><dd className="mt-1 font-mono">{money(selected.gross)}</dd></div></dl></section><section className="rounded-2xl border border-[#e6e3dc] p-4"><p className="text-sm font-extrabold">Custos e referências</p><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">MDR</dt><dd className="mt-1 font-mono">{money(selected.mdr)}</dd></div><div><dt className="text-xs text-muted-foreground">Antecipação informada</dt><dd className="mt-1 font-mono">{money(selected.anticipationFee)}</dd></div><div><dt className="text-xs text-muted-foreground">Desconto adicional calculado</dt><dd className="mt-1 font-mono">{money(selected.additionalDiscount)}</dd></div><div><dt className="text-xs text-muted-foreground">PaymentId</dt><dd className="mt-1 break-all font-mono text-xs">{selected.paymentId ?? "não informado"}</dd></div><div className="sm:col-span-2"><dt className="text-xs text-muted-foreground">Arquivo de origem</dt><dd className="mt-1 break-all font-mono text-xs">{selected.originalFileId ?? "não localizado"}</dd></div></dl>{selected.reason ? <p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">{selected.reason}</p> : null}</section><div className="flex items-center gap-2 text-sm text-muted-foreground"><CalendarClock className="h-4 w-4" />Vencimento informado pela Stone na antecipação: {date(selected.providerOriginalDueDate)}</div></div></> : null}</SheetContent></Sheet>
  </PageContainer>;
}
