"use client";

import { useState } from "react";
import { ArrowRight, CalendarClock } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { PageContainer } from "@/components/layout/page-container";
import { PageHero } from "@/components/patterns/page-hero";
import { HeroBackButton } from "@/components/patterns/hero-back-button";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { SidePanel, PanelSection } from "@/components/patterns/side-panel";
import { LiftRow } from "@/components/patterns/lift-row";
import { AnticipationWorkspace } from "@/features/financial/agent/anticipation-workspace";
import { formatStoneMoney } from "@/features/financial/agent/presentation";
import { FinancialAnalysisNavigation } from "@/features/financial/agent/analysis-navigation";
import type { StoneAnticipationReview } from "@/lib/integrations/stone/anticipation-review";

const money = formatStoneMoney;
const date = (value: string | null) => value ? value.split("-").reverse().join("/") : "Não informada";
const statuses = { paid_early: "Pago antes do vencimento", regular_payment: "Pagamento no prazo ou posterior", needs_review: "Revisar vínculo" };
const tone = { paid_early: "border-ds-border bg-ds-info-bg text-ds-info", regular_payment: "border-ds-border bg-ds-ok-bg text-ds-ok", needs_review: "border-ds-alert-border bg-ds-warn-bg text-ds-alert-ink" };
function daysEarly(due: string | null, paid: string | null) { if (!due || !paid) return null; return Math.round((Date.parse(`${due}T12:00:00Z`) - Date.parse(`${paid}T12:00:00Z`)) / 86_400_000); }

export function StoneAnticipationsPage({ agentEntry = false }: { agentEntry?: boolean }) {
  const { isDefaultAdmin } = useAuth(); const [result, setResult] = useState<StoneAnticipationReview | null>(null); const [page, setPage] = useState(0); const [filter, setFilter] = useState<"all" | keyof typeof statuses>("all"); const [selected, setSelected] = useState<StoneAnticipationReview["rows"][number] | null>(null);
  if (!isDefaultAdmin) return <PageContainer surface><p role="alert">Consulta restrita à administração.</p></PageContainer>;
  const ordered = result ? result.rows.filter(row => filter === "all" || row.status === filter).sort((left, right) => ({ paid_early: 0, needs_review: 1, regular_payment: 2 })[left.status] - ({ paid_early: 0, needs_review: 1, regular_payment: 2 })[right.status] || left.transactionId.localeCompare(right.transactionId)) : [];
  const filters: Array<{ id: "all" | keyof typeof statuses; label: string; count: number }> = result ? [{ id: "all", label: "Todas", count: result.rows.length }, { id: "paid_early", label: "Pagas antes do prazo", count: result.summary.earlyCount }, { id: "needs_review", label: "Pendentes de conferência", count: result.summary.pendingCount }, { id: "regular_payment", label: "No prazo ou posteriores", count: result.summary.regularCount }] : [];
  return <PageContainer variant="wide" surface className="space-y-6 py-6">
    {agentEntry ? <PageHero kicker="Financeiro · Análises" title="Coala Financeiro" subtitle="Análises guiadas de antecipações e recebíveis por período. Carteira completa, DRE e análise geral de caixa ainda não estão disponíveis neste agente." /> : <PageHero kicker="Conciliação · Recebimentos" title="Conferência de antecipações Stone" subtitle="Pagamentos comparados com parcelas originais, sem baixa ou lançamento financeiro." actions={<HeroBackButton fallbackHref="/dashboard/financial/stone-receipts" parentLabel="Conciliação de recebimentos" />} />}
    {agentEntry ? <FinancialAnalysisNavigation topic="anticipations" /> : null}
    <div role="note" className="rounded-2xl border border-ds-alert-border bg-ds-warn-bg p-4 text-sm text-ds-alert-ink">Custo informado no XML e desconto adicional calculado são evidências distintas. A entrada bancária não é conciliada nesta etapa; confirme o líquido em Crédito bancário × Stone.</div>
    <AnticipationWorkspace onResult={value => { setResult(value); setPage(0); setFilter("all"); setSelected(null); }} />
    {result ? <section className="space-y-4" aria-label="Resultado da conferência"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm text-muted-foreground">StoneCode {result.stoneCode} · pagamentos de {date(result.referenceDate)} · consulta {new Date(result.collectedAt).toLocaleString("pt-BR")}</p><p className="text-sm text-muted-foreground">Arquivo {result.paymentFileId}</p></div>{result.unavailableDates.length || result.skippedDates.length ? <p role="alert" className="rounded-xl border border-ds-confirm-border bg-ds-danger-bg p-3 text-sm text-ds-confirm-ink"><strong>Cobertura incompleta.</strong> Datas indisponíveis: {result.unavailableDates.map(date).join(", ") || "nenhuma"}. Datas fora do limite: {result.skippedDates.map(date).join(", ") || "nenhuma"}. Não conclua ausência de antecipação nas parcelas pendentes.</p> : null}
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["Parcelas pagas antes do prazo", String(result.summary.earlyCount), "border-ds-border bg-ds-info-bg"], ["Bruto dessas parcelas", money(result.summary.gross), "border-ds-border bg-white"], ["Líquido informado pela Stone", money(result.summary.paidNet), "border-ds-border bg-ds-ok-bg"], ["Desconto adicional calculado", money(result.summary.additionalDiscount), "border-ds-confirm-border bg-ds-danger-bg"]].map(([title, value, className]) => <Card key={title} className={`rounded-2xl ${className}`}><CardContent className="p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-muted-foreground">{title}</p><p className="mt-2 font-mono text-xl font-bold">{value}</p></CardContent></Card>)}</div>
      <div className="grid gap-3 rounded-2xl border border-ds-border bg-ds-input p-4 text-sm sm:grid-cols-3"><p><strong>MDR informado</strong><span className="mt-1 block font-mono">{money(result.summary.mdr)}</span></p><p><strong>Custo de antecipação no XML</strong><span className="mt-1 block font-mono">{money(result.summary.anticipationFee)}</span></p><p><strong>Diferença não explicada</strong><span className="mt-1 block font-mono">{money(result.summary.unexplainedDifference)}</span></p></div>
      <div role="group" aria-label="Filtrar parcelas" className="flex flex-wrap gap-2">{filters.map(item => <button key={item.id} type="button" onClick={() => { setFilter(item.id); setPage(0); }} aria-pressed={filter === item.id} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${filter === item.id ? "border-ds-dark bg-ds-dark text-white" : "border-ds-border bg-white text-ds-ink-2"}`}>{item.label} <span className="ml-1 opacity-70">{item.count}</span></button>)}</div>
      <section className="rounded-ds-card border border-ds-border bg-ds-surface"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-ds-divider bg-ds-input px-4 py-3"><div><h2 className="text-sm font-extrabold">Parcelas e evidências do pagamento</h2><p className="mt-1 text-xs text-muted-foreground">Clique em uma linha para ver as evidências completas.</p></div><span className="text-xs text-muted-foreground">{ordered.length ? `${page * 50 + 1}–${Math.min(ordered.length, (page + 1) * 50)} de ${ordered.length}` : ""}</span></div>{ordered.length ? <div className="divide-y divide-ds-divider">{ordered.slice(page * 50, (page + 1) * 50).map(row => { const early = daysEarly(row.originalDueDate, row.paymentDate); return <LiftRow key={`${row.transactionId}:${row.installment}`} onClick={() => setSelected(row)} className="grid w-full gap-3 text-left md:grid-cols-[minmax(180px,1fr)_minmax(220px,1.1fr)_120px_150px] md:items-center"><div><p className="font-mono text-xs font-semibold">{row.transactionId} / {row.installment}</p><p className="mt-1 text-xs text-muted-foreground">Venda {date(row.saleDate)} · bruto {money(row.gross)}</p></div><div><p className="text-sm font-semibold">{date(row.originalDueDate)} <ArrowRight className="mx-1 inline h-3.5 w-3.5" aria-hidden="true" /> {date(row.paymentDate)}</p><p className="mt-1 text-xs text-muted-foreground">{row.status === "paid_early" && early !== null ? `${early} dia(s) antes do vencimento` : "pagamento no arquivo Stone"}</p></div><span className="font-mono text-sm font-bold">{money(row.paidNet)}</span><span className={`justify-self-start rounded-full border px-2 py-1 text-[11px] font-bold ${tone[row.status]}`}>{statuses[row.status]}</span></LiftRow>; })}</div> : <div role="status" className="px-6 py-12 text-center text-sm text-muted-foreground">{result.rows.length ? "Nenhuma parcela corresponde ao filtro selecionado." : "Nenhuma parcela com evento de pagamento neste arquivo. Isso não comprova ausência de antecipações em outros arquivos."}</div>}{ordered.length > 50 ? <div className="flex items-center justify-end gap-3 border-t border-ds-divider px-4 py-3"><Button type="button" variant="outline" disabled={page === 0} onClick={() => setPage(page - 1)}>Anterior</Button><span className="text-sm">Página {page + 1} de {Math.ceil(ordered.length / 50)}</span><Button type="button" variant="outline" disabled={(page + 1) * 50 >= ordered.length} onClick={() => setPage(page + 1)}>Próxima</Button></div> : null}</section>
      <p className="text-xs text-muted-foreground">Totais somados na precisão original; linhas exibidas com duas casas decimais. Nenhuma alteração na agenda, no caixa ou na DRE.</p>
    </section> : null}
    {selected ? <SidePanel open onOpenChange={open => { if (!open) setSelected(null); }} kicker="Parcela" title={`${selected.transactionId} / ${selected.installment}`} subtitle={`${statuses[selected.status]}${selected.providerAnticipationConfirmed ? " · antecipação explícita no XML" : ""}`}>
      <PanelSection title="Datas e valores"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-ds-ink-faint">Venda</dt><dd className="mt-1">{date(selected.saleDate)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Vencimento original</dt><dd className="mt-1">{date(selected.originalDueDate)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Pagamento Stone</dt><dd className="mt-1">{date(selected.paymentDate)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Líquido pago</dt><dd className="mt-1 font-mono font-semibold">{money(selected.paidNet)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Líquido original</dt><dd className="mt-1 font-mono">{money(selected.originalNet)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Bruto</dt><dd className="mt-1 font-mono">{money(selected.gross)}</dd></div></dl></PanelSection>
      <PanelSection title="Custos e referências"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-ds-ink-faint">MDR</dt><dd className="mt-1 font-mono">{money(selected.mdr)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Antecipação informada</dt><dd className="mt-1 font-mono">{money(selected.anticipationFee)}</dd></div><div><dt className="text-xs text-ds-ink-faint">Desconto adicional calculado</dt><dd className="mt-1 font-mono">{money(selected.additionalDiscount)}</dd></div><div><dt className="text-xs text-ds-ink-faint">PaymentId</dt><dd className="mt-1 break-all font-mono text-xs">{selected.paymentId ?? "não informado"}</dd></div><div className="sm:col-span-2"><dt className="text-xs text-ds-ink-faint">Arquivo de origem</dt><dd className="mt-1 break-all font-mono text-xs">{selected.originalFileId ?? "não localizado"}</dd></div></dl>{selected.reason ? <p className="mt-3 rounded-xl border border-ds-alert-border bg-ds-alert-bg p-3 text-sm text-ds-alert-ink">{selected.reason}</p> : null}</PanelSection>
      <div className="flex items-center gap-2 text-sm text-ds-ink-muted"><CalendarClock className="h-4 w-4" />Vencimento informado pela Stone na antecipação: {date(selected.providerOriginalDueDate)}</div>
    </SidePanel> : null}
  </PageContainer>;
}
