export const EMPLOYEE_DOCUMENT_CATEGORIES = [
  { id: "personal", label: "Cadastro e identificação" },
  { id: "admission", label: "Admissão e registro" },
  { id: "contracts", label: "Contratos e alterações" },
  { id: "work_schedule", label: "Jornada, ponto e escalas" },
  { id: "remuneration", label: "Remuneração" },
  { id: "benefits", label: "Benefícios" },
  { id: "occupational_health", label: "Saúde e segurança ocupacional" },
  { id: "vacations", label: "Férias" },
  { id: "leaves", label: "Afastamentos e licenças" },
  { id: "uniforms", label: "Uniformes, equipamentos e responsabilidades" },
  { id: "training", label: "Treinamentos, avaliações e comunicações" },
  { id: "warnings", label: "Medidas disciplinares" },
  { id: "termination", label: "Desligamento" },
  { id: "pending_classification", label: "Pendentes de classificação" },
] as const;

export type EmployeeDocumentCategoryId = (typeof EMPLOYEE_DOCUMENT_CATEGORIES)[number]["id"];
export type EmployeeDocumentAccessLevelId = (typeof EMPLOYEE_DOCUMENT_ACCESS_LEVELS)[number]["id"];

export const EMPLOYEE_DOCUMENT_TYPES_BY_CATEGORY: Record<EmployeeDocumentCategoryId, readonly string[]> = {
  personal: [
    "Documento de identificação",
    "CPF",
    "CNH",
    "Comprovante de residência",
    "Título de eleitor",
    "Certidão de nascimento/casamento",
    "Dados bancários",
    "Documento de dependente",
    "Foto 3x4",
    "Outro documento pessoal",
  ],
  admission: [
    "Ficha cadastral",
    "Ficha de registro",
    "Carteira de trabalho",
    "PIS/PASEP",
    "Declaração de dependentes",
    "Termo de ciência/LGPD",
    "Outro documento de admissão",
  ],
  contracts: [
    "Contrato de experiência",
    "Contrato de trabalho",
    "Prorrogação de contrato",
    "Aditivo contratual",
    "Termo de confidencialidade",
    "Outro contrato",
  ],
  work_schedule: [
    "Espelho de ponto",
    "Escala de trabalho",
    "Ajuste de ponto",
    "Banco de horas",
    "Horas extras",
    "Outro documento de jornada",
  ],
  remuneration: [
    "Contracheque",
    "Comprovante de pagamento",
    "Recibo",
    "Adiantamento",
    "Comissão/bonificação",
    "Informe de rendimentos",
    "Outro documento de remuneração",
  ],
  occupational_health: [
    "ASO admissional",
    "ASO periódico",
    "ASO de retorno ao trabalho",
    "ASO de mudança de risco/função",
    "ASO demissional",
    "Exames complementares",
    "Outro documento ocupacional",
  ],
  benefits: [
    "Solicitação de vale-transporte",
    "Termo de opção de vale-transporte",
    "Declaração de trajeto",
    "Recibo de cartão",
    "Suspensão/cancelamento de vale-transporte",
    "Termo de benefícios",
    "Plano de saúde",
    "Seguro de vida",
    "Salário-família",
    "Declaração de benefício",
    "Outro documento de benefício",
  ],
  uniforms: [
    "Termo de entrega de uniforme",
    "Termo de devolução de uniforme",
    "Termo de entrega de equipamento",
    "Termo de devolução de equipamento",
    "Controle de troca",
    "Termo de responsabilidade",
    "Registro de dano ou avaria",
    "Outro documento de uniforme",
  ],
  vacations: [
    "Aviso de férias",
    "Recibo de férias",
    "Solicitação de férias",
    "Abono pecuniário",
    "Alteração/cancelamento de férias",
    "Comprovante de pagamento de férias",
    "Outro documento de férias",
  ],
  leaves: [
    "Atestado médico",
    "Declaração de comparecimento",
    "Licença maternidade",
    "Licença paternidade",
    "Afastamento previdenciário",
    "Documento de retorno ao trabalho",
    "Outro documento de afastamento",
  ],
  warnings: [
    "Advertência",
    "Suspensão disciplinar",
    "Manifestação do colaborador",
    "Relatório de ocorrência",
    "Apuração interna",
    "Outro documento disciplinar",
  ],
  training: [
    "Certificado de treinamento",
    "Avaliação",
    "Feedback formal",
    "Comunicado",
    "Ciência de política",
    "Registro de reunião",
    "Plano de desenvolvimento",
    "Outro documento de treinamento",
  ],
  termination: [
    "Pedido de demissão",
    "Aviso prévio",
    "Termo de rescisão",
    "GRRF/FGTS",
    "Seguro-desemprego",
    "ASO demissional",
    "Termo de devolução de bens",
    "Quitação/recibo",
    "Comprovante de pagamento rescisório",
    "Outro documento de desligamento",
  ],
  pending_classification: [
    "Documento não identificado",
    "Declaração",
    "Comprovante",
    "Documento complementar",
    "Outro documento",
  ],
};

export const EMPLOYEE_DOCUMENT_STATUSES = [
  { id: "pending", label: "Pendente" },
  { id: "received", label: "Recebido" },
  { id: "validated", label: "Validado" },
  { id: "rejected", label: "Recusado" },
] as const;

export const EMPLOYEE_DOCUMENT_ACCESS_LEVELS = [
  { id: "unrestricted", label: "Sem restrição" },
  { id: "partial", label: "Restrito parcial" },
  { id: "restricted", label: "Restrito total" },
  { id: "confidential", label: "Confidencial" },
] as const;

export type EmployeeDocumentTypeConfig = {
  code: string;
  label: string;
  category: EmployeeDocumentCategoryId;
  folderCode: string;
  defaultAccessLevel: EmployeeDocumentAccessLevelId;
  aliases: string[];
  classificationHints: string[];
};

export const EMPLOYEE_DOCUMENT_TYPE_CATALOG = [
  {
    code: "UNKNOWN_DOCUMENT",
    label: "Documento não identificado",
    category: "pending_classification",
    folderCode: "PENDING_CLASSIFICATION",
    defaultAccessLevel: "restricted",
    aliases: ["desconhecido", "não identificado"],
    classificationHints: ["Use quando nenhum tipo cadastrado for adequado."],
  },
  {
    code: "PERSONAL_ID",
    label: "Documento de identificação",
    category: "personal",
    folderCode: "REGISTRATION_IDENTIFICATION",
    defaultAccessLevel: "restricted",
    aliases: ["rg", "cin", "identidade", "cnh"],
    classificationHints: ["Documento oficial com foto ou identificação civil."],
  },
  {
    code: "ADDRESS_PROOF",
    label: "Comprovante de residência",
    category: "personal",
    folderCode: "REGISTRATION_IDENTIFICATION",
    defaultAccessLevel: "restricted",
    aliases: ["conta de luz", "conta de água", "residência", "endereço"],
    classificationHints: ["Comprova endereço do colaborador."],
  },
  {
    code: "EMPLOYEE_REGISTRATION",
    label: "Ficha de registro",
    category: "admission",
    folderCode: "ADMISSION_REGISTRATION",
    defaultAccessLevel: "restricted",
    aliases: ["registro de empregado", "ficha funcional"],
    classificationHints: ["Ficha formal de registro/admissão do empregado."],
  },
  {
    code: "EMPLOYMENT_CONTRACT",
    label: "Contrato de trabalho",
    category: "contracts",
    folderCode: "CONTRACTS_CHANGES",
    defaultAccessLevel: "restricted",
    aliases: ["contrato inicial", "contrato empregado"],
    classificationHints: ["Contrato laboral sem foco exclusivo em experiência."],
  },
  {
    code: "PROBATION_CONTRACT",
    label: "Contrato de experiência",
    category: "contracts",
    folderCode: "CONTRACTS_CHANGES",
    defaultAccessLevel: "restricted",
    aliases: ["experiência", "contrato experimental"],
    classificationHints: ["Contrato com prazo de experiência."],
  },
  {
    code: "PROBATION_EXTENSION",
    label: "Prorrogação de contrato",
    category: "contracts",
    folderCode: "CONTRACTS_CHANGES",
    defaultAccessLevel: "restricted",
    aliases: ["prorrogação experiência", "aditivo de experiência"],
    classificationHints: ["Prorroga contrato de experiência."],
  },
  {
    code: "PAYSLIP",
    label: "Contracheque",
    category: "remuneration",
    folderCode: "REMUNERATION",
    defaultAccessLevel: "confidential",
    aliases: ["holerite", "demonstrativo de pagamento", "folha de pagamento"],
    classificationHints: ["Demonstra proventos, descontos, líquido e competência."],
  },
  {
    code: "TRANSPORT_REQUEST",
    label: "Solicitação de vale-transporte",
    category: "benefits",
    folderCode: "BENEFITS",
    defaultAccessLevel: "partial",
    aliases: ["vale transporte", "opção de vale-transporte", "declaração de trajeto"],
    classificationHints: ["Solicitação, opção ou declaração relacionada ao vale-transporte."],
  },
  {
    code: "DEPENDENT_DOCUMENT",
    label: "Documento de dependente",
    category: "personal",
    folderCode: "REGISTRATION_IDENTIFICATION",
    defaultAccessLevel: "restricted",
    aliases: ["certidão de nascimento", "nascimento do filho", "documento do dependente", "cpf do dependente"],
    classificationHints: ["Documento que comprova filho ou dependente equiparado para cadastro e salário-família."],
  },
  {
    code: "FAMILY_SALARY_TERM",
    label: "Termo de responsabilidade salário-família",
    category: "benefits",
    folderCode: "BENEFITS",
    defaultAccessLevel: "restricted",
    aliases: ["termo de responsabilidade", "salário família", "salario familia"],
    classificationHints: ["Termo, declaração ou requerimento usado para salário-família."],
  },
  {
    code: "VACCINATION_RECORD",
    label: "Caderneta de vacinação",
    category: "benefits",
    folderCode: "BENEFITS",
    defaultAccessLevel: "restricted",
    aliases: ["vacinação", "caderneta de vacina", "cartão de vacina", "cartao de vacina"],
    classificationHints: ["Comprovação de vacinação de dependente para salário-família."],
  },
  {
    code: "SCHOOL_ATTENDANCE",
    label: "Comprovante de frequência escolar",
    category: "benefits",
    folderCode: "BENEFITS",
    defaultAccessLevel: "restricted",
    aliases: ["frequência escolar", "frequencia escolar", "declaração escolar", "comprovante escolar"],
    classificationHints: ["Comprovação de frequência escolar de dependente para salário-família."],
  },
  {
    code: "ASO_ADMISSION",
    label: "ASO admissional",
    category: "occupational_health",
    folderCode: "OCCUPATIONAL_HEALTH_SAFETY",
    defaultAccessLevel: "confidential",
    aliases: ["atestado de saúde ocupacional admissional"],
    classificationHints: ["ASO com tipo de exame admissional."],
  },
  {
    code: "ASO_PERIODIC",
    label: "ASO periódico",
    category: "occupational_health",
    folderCode: "OCCUPATIONAL_HEALTH_SAFETY",
    defaultAccessLevel: "confidential",
    aliases: ["atestado de saúde ocupacional periódico"],
    classificationHints: ["ASO com tipo de exame periódico."],
  },
  {
    code: "ASO_RETURN",
    label: "ASO de retorno ao trabalho",
    category: "occupational_health",
    folderCode: "OCCUPATIONAL_HEALTH_SAFETY",
    defaultAccessLevel: "confidential",
    aliases: ["atestado de saúde ocupacional retorno", "aso retorno", "retorno ao trabalho"],
    classificationHints: ["ASO emitido antes do retorno ao trabalho após afastamento."],
  },
  {
    code: "ASO_RISK_CHANGE",
    label: "ASO de mudança de risco/função",
    category: "occupational_health",
    folderCode: "OCCUPATIONAL_HEALTH_SAFETY",
    defaultAccessLevel: "confidential",
    aliases: ["aso mudança de risco", "aso mudanca de risco", "mudança de função", "mudanca de função"],
    classificationHints: ["ASO emitido por mudança de risco ocupacional ou função."],
  },
  {
    code: "ASO_DISMISSAL",
    label: "ASO demissional",
    category: "occupational_health",
    folderCode: "OCCUPATIONAL_HEALTH_SAFETY",
    defaultAccessLevel: "confidential",
    aliases: ["atestado de saúde ocupacional demissional", "aso demissional"],
    classificationHints: ["ASO emitido no desligamento do colaborador."],
  },
  {
    code: "VACATION_NOTICE",
    label: "Aviso de férias",
    category: "vacations",
    folderCode: "VACATIONS",
    defaultAccessLevel: "restricted",
    aliases: ["comunicado de férias", "notificação de férias"],
    classificationHints: ["Comunica concessão, datas de gozo e período aquisitivo; não é recibo de valores."],
  },
  {
    code: "VACATION_RECEIPT",
    label: "Recibo de férias",
    category: "vacations",
    folderCode: "VACATIONS",
    defaultAccessLevel: "restricted",
    aliases: ["recibo férias", "demonstrativo férias"],
    classificationHints: ["Contém verbas, quitação ou recebimento de férias."],
  },
  {
    code: "VACATION_PAYMENT",
    label: "Comprovante de pagamento de férias",
    category: "vacations",
    folderCode: "VACATIONS",
    defaultAccessLevel: "confidential",
    aliases: ["pagamento de férias", "comprovante bancário férias"],
    classificationHints: ["Comprova transferência ou pagamento de férias."],
  },
  {
    code: "MEDICAL_CERTIFICATE",
    label: "Atestado médico",
    category: "leaves",
    folderCode: "LEAVES_LICENSES",
    defaultAccessLevel: "confidential",
    aliases: ["atestado", "declaração médica"],
    classificationHints: ["Afastamento ou comparecimento médico. Não extrair diagnóstico sem necessidade."],
  },
  {
    code: "UNIFORM_DELIVERY",
    label: "Termo de entrega de uniforme",
    category: "uniforms",
    folderCode: "UNIFORMS_EQUIPMENT_RESPONSIBILITIES",
    defaultAccessLevel: "partial",
    aliases: ["entrega de uniforme", "recibo de uniforme"],
    classificationHints: ["Entrega de uniforme, EPI ou item de responsabilidade."],
  },
  {
    code: "DISCIPLINARY_WARNING",
    label: "Advertência",
    category: "warnings",
    folderCode: "DISCIPLINARY_MEASURES",
    defaultAccessLevel: "confidential",
    aliases: ["advertência disciplinar", "comunicação disciplinar"],
    classificationHints: ["Medida disciplinar por conduta ou descumprimento."],
  },
  {
    code: "RESIGNATION_REQUEST",
    label: "Pedido de demissão",
    category: "termination",
    folderCode: "TERMINATION",
    defaultAccessLevel: "confidential",
    aliases: ["carta de demissão", "solicitação de desligamento"],
    classificationHints: ["Pedido espontâneo do colaborador para encerrar vínculo."],
  },
  {
    code: "TERMINATION_NOTICE",
    label: "Aviso prévio",
    category: "termination",
    folderCode: "TERMINATION",
    defaultAccessLevel: "confidential",
    aliases: ["aviso-prévio", "comunicação de aviso"],
    classificationHints: ["Documento de aviso-prévio trabalhado ou indenizado."],
  },
  {
    code: "TERMINATION_TERM",
    label: "Termo de rescisão",
    category: "termination",
    folderCode: "TERMINATION",
    defaultAccessLevel: "confidential",
    aliases: ["trct", "rescisão contratual", "termo de rescisão do contrato de trabalho"],
    classificationHints: ["TRCT ou termo formal de rescisão."],
  },
  {
    code: "TERMINATION_PAYMENT",
    label: "Comprovante de pagamento rescisório",
    category: "termination",
    folderCode: "TERMINATION",
    defaultAccessLevel: "confidential",
    aliases: ["pagamento rescisório", "comprovante rescisão"],
    classificationHints: ["Comprova pagamento ligado à rescisão."],
  },
] as const satisfies readonly EmployeeDocumentTypeConfig[];

export function employeeDocumentTypeConfigByCode(code: string | null | undefined) {
  return EMPLOYEE_DOCUMENT_TYPE_CATALOG.find((item) => item.code === code) ?? EMPLOYEE_DOCUMENT_TYPE_CATALOG[0];
}

export function employeeDocumentTypeConfigByLabel(label: string | null | undefined) {
  return EMPLOYEE_DOCUMENT_TYPE_CATALOG.find((item) => item.label === label);
}

export function isEmployeeDocumentCategory(value: string): value is EmployeeDocumentCategoryId {
  return EMPLOYEE_DOCUMENT_CATEGORIES.some((category) => category.id === value);
}

export function isEmployeeDocumentType(category: EmployeeDocumentCategoryId, value: string) {
  return EMPLOYEE_DOCUMENT_TYPES_BY_CATEGORY[category].includes(value);
}
