'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, FileUp } from 'lucide-react';

type Info = { candidateName: string; examType: 'admission' | 'dismissal'; uploadEnabled: boolean; uploadOpensOn: string; alreadyUploaded: boolean };
function displayDate(value: string) { const [y, m, d] = value.split('-'); return y && m && d ? `${d}/${m}/${y}` : value; }

export default function CandidateAsoPage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [info, setInfo] = useState<Info | null>(null); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { void params.then(({ token: value }) => { setToken(value); return fetch(`/api/hr/aso/candidate/${value}`, { cache: 'no-store' }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInfo(data); }).catch(caught => setError(caught instanceof Error ? caught.message : 'Falha ao abrir o link.')); }); }, [params]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const response = await fetch(`/api/hr/aso/candidate/${token}`, { method: 'POST', body: new FormData(event.currentTarget) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error || 'Falha ao enviar.'); setSent(true); }
  const examLabel = info?.examType === 'dismissal' ? 'demissional' : 'admissional';
  return <main className="min-h-screen bg-[#fff8fc] px-4 py-10 text-slate-900"><div className="mx-auto max-w-xl rounded-3xl border border-pink-100 bg-white p-6 shadow-xl shadow-pink-100/50 sm:p-9"><p className="text-sm font-black uppercase tracking-widest text-pink-500">Coala Shakes · ASO {examLabel}</p><h1 className="mt-3 text-2xl font-black">Enviar ASO</h1><p className="mt-2 text-sm text-slate-600">Olá, <b>{info?.candidateName || 'colaborador(a)'}</b>. Este link serve exclusivamente para anexar o documento emitido após o exame {examLabel}.</p>{error ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p> : null}{info ? <>{sent || info.alreadyUploaded ? <div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-800"><CheckCircle2 className="h-7 w-7"/><p className="mt-2 font-black">ASO recebido.</p><p className="mt-1 text-sm">O RH fará a conferência do documento.</p></div> : info.uploadEnabled ? <form onSubmit={submit} className="mt-6 space-y-4"><label className="block rounded-2xl border-2 border-dashed p-5 text-center text-sm font-bold"><FileUp className="mx-auto mb-2 h-7 w-7 text-pink-500"/>Anexe o ASO em PDF, JPG ou PNG<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required className="mt-3 block w-full text-xs"/></label><button disabled={busy} className="h-12 w-full rounded-xl bg-pink-500 font-black text-white disabled:opacity-50">{busy ? 'Enviando...' : 'Enviar ASO'}</button></form> : <p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800">O envio do ASO será liberado em {displayDate(info.uploadOpensOn)}, no dia do exame.</p>}</> : !error ? <p className="mt-6 text-sm">Carregando...</p> : null}</div></main>;
}
