const SAFE_UBER_ERROR_CODES = new Set([
  'UBER_CSV_HEADER_UNRECOGNIZED',
  'UBER_CSV_PARSE_FAILED',
  'UBER_CSV_DATE_ORDER_INCONSISTENT',
  'UBER_CSV_NO_VALID_TRIPS',
  'UBER_CSV_INVALID_RIDE_ROW',
  'UBER_CSV_ROW_LIMIT_EXCEEDED',
  'UBER_SFTP_FILE_SIZE_INVALID',
  'UBER_SFTP_USERNAME_REQUIRED',
  'UBER_SFTP_PRIVATE_KEY_REQUIRED',
  'UBER_SFTP_HOST_FINGERPRINT_REQUIRED',
  'UBER_SFTP_HOST_FINGERPRINT_INVALID',
  'UBER_TRIP_TRANSACTION_LIMIT_EXCEEDED',
  'UBER_RECONCILIATION_CANDIDATE_LIMIT_EXCEEDED',
]);

export function safeUberErrorCode(error: unknown) {
  const message = error instanceof Error ? error.message : '';
  return SAFE_UBER_ERROR_CODES.has(message) ? message : 'UBER_UNEXPECTED_ERROR';
}
