"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { terminationFetch } from "./client";
import type { CltTerminationProcess, TerminationEvent, TerminationStepStatus } from "./types";

export function TerminationDetailPage({ id }: { id: string }) {
  const { firebaseUser } = useAuth();
  const [process, setProcess] = useState<CltTerminationProcess | null>(null);
  const [events, setEvents] = useState<TerminationEvent[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [decision, setDecision] = useState("worked");
  const [communicationDate, setCommunicationDate] = useState(new Date().toISOString().slice(0, 10));
  const [contractEndDate, setContractEndDate] = useState(new Date().toISOString().slice(0, 10));
  const [accountantEmail, setAccountantEmail] = useState("");
  const [selectedDocumentIds, setSelectedDocumentIds] = useState<string[]>([]);
  const load = useCallback(async () => { if (!firebaseUser) return; const data = await terminationFetch<{ process: CltTerminationProcess; events: TerminationEvent[] }>(firebaseUser, `/api/hr/terminations/${id}`); setProcess(data.process); setEvents(data.events); }, [firebaseUser, id]);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function action(body: Record<string, unknown>) { if (!firebaseUser) return; setBusy(true); setError(null); try { await terminationFetch(firebaseUser, `/api/hr/terminations/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Falha."); } finally { setBusy(false); } }
  if (!process) return <div className="p-8 text-muted-foreground">{error ?? "Carregando..."}</div>;
  return <div className="space-y-6 p-4 md:p-8">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{process.employeeName}</h1><p className="text-muted-foreground">{process.request.protocol} · {process.currentSummary}</p></div><Badge>{process.health}</Badge></div>
    <Card><CardContent className="space-y-2 p-5"><Progress value={process.progress}/><div className="flex justify-between text-sm"><span>{process.progress}% concluído</span><span>{process.notice ? `Prazo legal: ${new Date(`${process.notice.legalPaymentDueDate}T12:00:00`).toLocaleDateString("pt-BR")}` : "Prazo aguardando definição do aviso"}</span></div></CardContent></Card>
    {error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    {process.status === "hr_review" && <Card><CardHeader><CardTitle className="text-base">Validação do RH</CardTitle></CardHeader><CardContent><Button disabled={busy} onClick={() => action({ action: "validate" })}>Validar pedido e iniciar trilhas paralelas</Button></CardContent></Card>}
    {process.hrValidation?.status === "confirmed" && !process.notice && <Card><CardHeader><CardTitle className="text-base">Definir aviso-prévio</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><Select value={decision} onValueChange={setDecision}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="worked">Trabalhado</SelectItem><SelectItem value="waived_no_discount">Dispensado sem desconto</SelectItem><SelectItem value="waived_with_discount">Dispensado com desconto</SelectItem><SelectItem value="exception_review">Exceção</SelectItem></SelectContent></Select><Input type="date" value={communicationDate} onChange={(e) => setCommunicationDate(e.target.value)}/>{decision !== "worked" && <Input type="date" value={contractEndDate} onChange={(e) => setContractEndDate(e.target.value)}/>}<Button disabled={busy} onClick={() => action({ action: "decide_notice", decision, communicationDate, contractEndDate })}>Confirmar aviso</Button></CardContent></Card>}
    {process.hrValidation?.status === "confirmed" && <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">ASO demissional — fluxo paralelo</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Gerar guia, criar PIX no Inter, aguardar aprovação/pagamento, anexar comprovante, enviar à clínica e confirmar o agendamento.</p><Button asChild variant="outline"><Link href={`/dashboard/hr/recruitment/integration?process=${process.id}`}>Abrir operação do ASO</Link></Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Contabilidade</CardTitle></CardHeader><CardContent className="space-y-3"><Input type="email" placeholder="E-mail da contabilidade" value={accountantEmail} onChange={(e) => setAccountantEmail(e.target.value)}/><Button disabled={busy || !process.notice || !accountantEmail} onClick={() => action({ action: "send_accountant", recipientEmail: accountantEmail })}>Enviar resumo e portal de arquivos</Button><p className="text-xs text-muted-foreground">O link é individual, auditado e expira em 30 dias.</p></CardContent></Card></div>}
    {process.documents.some((document) => document.type === "accountant_document" || document.type === "signed_document") && <Card><CardHeader><CardTitle className="text-base">Auditoria e documentos para o colaborador</CardTitle></CardHeader><CardContent className="space-y-3">{process.documents.filter((document) => document.type === "accountant_document" || document.type === "signed_document").map((document) => <label key={document.id} className="flex items-center gap-3 rounded-md border p-3 text-sm"><input type="checkbox" checked={document.selectedForEmployee || selectedDocumentIds.includes(document.id)} disabled={document.type === "signed_document"} onChange={(event) => setSelectedDocumentIds((current) => event.target.checked ? [...new Set([...current, document.id])] : current.filter((id) => id !== document.id))}/><span className="flex-1">{document.label}</span><Badge variant="outline">{document.auditStatus}</Badge></label>)}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => { const approvedIds = process.documents.filter((document) => document.type === "accountant_document").map((document) => document.id); void action({ action: "audit_documents", approvedIds, selectedIds: selectedDocumentIds }); }}>Aprovar auditoria e salvar seleção</Button><Button disabled={busy || process.steps.find((step) => step.id === "document_audit")?.status !== "completed"} onClick={() => action({ action: "send_signatures" })}>Enviar para assinatura de ambos</Button></div><p className="text-xs text-muted-foreground">A assinatura eletrônica registra os dois signatários no mesmo documento e exige SMS do colaborador.</p></CardContent></Card>}
    <div className="grid gap-4 lg:grid-cols-2">{process.steps.map((step) => <Card key={step.id}><CardContent className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{step.label}</p><p className="text-xs text-muted-foreground">Responsável: {step.owner}{step.dueAt ? ` · até ${new Date(`${step.dueAt}T12:00:00`).toLocaleDateString("pt-BR")}` : ""}</p>{step.note && <p className="mt-1 text-xs">{step.note}</p>}</div>{["employee_request", "identity_signature", "hr_validation", "notice_decision", "closure"].includes(step.id) ? <Badge variant="outline">{step.status}</Badge> : <Select disabled={busy || process.status === "completed"} value={step.status} onValueChange={(status: TerminationStepStatus) => action({ action: "update_step", stepId: step.id, status })}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pending">Pendente</SelectItem><SelectItem value="in_progress">Em andamento</SelectItem><SelectItem value="waiting_external">Aguardando terceiro</SelectItem><SelectItem value="blocked">Bloqueado</SelectItem><SelectItem value="completed">Concluído</SelectItem><SelectItem value="waived">Dispensado</SelectItem></SelectContent></Select>}</CardContent></Card>)}</div>
    <div className="flex justify-end"><Button disabled={busy || process.status === "completed"} onClick={() => action({ action: "complete" })}>Concluir desligamento</Button></div>
    <Card><CardHeader><CardTitle className="text-base">Histórico auditável</CardTitle></CardHeader><CardContent className="space-y-3">{events.map((event) => <div key={event.id} className="border-l-2 pl-3"><p className="text-sm">{event.message}</p><p className="text-xs text-muted-foreground">{event.actorName} · {new Date(event.at).toLocaleString("pt-BR")}</p></div>)}</CardContent></Card>
  </div>;
}
